# SITE CONFIGURATION
baseurl: "/estephens6.github.io" # the subpath of your site, e.g. /blog/
url: "http://estephens6.github.io"  # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: ericCStephens
  avatar: avatar.png
  gravatar: # Email MD5 hash
  description: "A coding adventure blog with posts and pictures" # used by search engines

  # Header and footer text
  header_text: 
     <h1><font color = "white">Eric C Stephens</font> <font color = "orange">developer</font><font color = "white">Adventurer</font></h1>
  header_text_feature_image: "img/hktemple.JPG"
  footer_text: >
   Powered by <a href="http://ericcstephens.com">ericCStephens</a>

  # Icons
  rss: false
  email_address: "perkinsdrive@gmail.com"
  behance:
  bitbucket:
  dribbble: 
  facebook: "cire.snehpets"
  flickr:
  github: "estephens6"
  google_plus:
  instagram: "ericcstephens"
  linkedin:  "https://www.linkedin.com/in/ericcstephens"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "cirecode"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-77857739-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
