# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tyler.boddyspargo.com/portfolio" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Tyler BoddySpargo
  avatar: avatar.png
  gravatar: e6191afa959c270e9e593538141dd011
  description: "A portfolio of web development case studies." # used by search engines

  # Header and footer text
  header_text: >
     <h1>Developing a way to live.</h1>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>
  # Icons
  rss: false
  resume: resume
  email_address: #boddyspargo.tyler@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "tboddyspargo"
  google_plus:
  instagram:
  linkedin: https://www.linkedin.com/in/tylerboddyspargo/ # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # https://stackexchange.com/users/11291848/tyler-boddyspargo # Full URL
  steam:
  tumblr:
  twitter: # @tyler_bodd
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-103027689-1"
  disqus_shortname:
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: _sass
  style: :compressed

plugins: [jekyll-paginate]
